// ============================================================================
// Sovereign Node 9010 — ACL Section 56 Demand Generator (Task 3.1)
// Generates formal legal demand documents when structural deception is flagged
// ============================================================================

import type { DeceptionReport } from '../types.js';

export interface BBFBScore {
  law: { metric: string; value: number; threshold: number; passed: boolean }[];
  grace: { rawPenalty: number; normalizedPenalty: number; riskLevel: string };
  fruit: {
    compositeValueScore: number;
    weightedScores: { name: string; weighted: number }[];
    compliant: boolean;
    threshold: number;
  };
  overallCompliant: boolean;
}

export interface ACLDemandInput {
  invoiceSpec: string;
  hardwareId: string;
  consumerName?: string;
  supplierName?: string;
  deceptionReport: DeceptionReport;
  bbfbScore?: BBFBScore;
}

export function generateACLDemand(input: ACLDemandInput): string {
  const {
    invoiceSpec,
    hardwareId,
    consumerName = '[Consumer Name]',
    supplierName = '[Supplier Name]',
    deceptionReport,
    bbfbScore,
  } = input;

  const dateIssued = new Date().toISOString().split('T')[0];

  const patternLines = deceptionReport.detectedPatterns
    .map(
      (p) =>
        `- **${p.patternName}** (${p.patternId}): severity ${p.severity}, confidence ${(p.confidence * 100).toFixed(1)}%`,
    )
    .join('\n');

  const reasoningLines = deceptionReport.forensicReasoning.map((r) => `- ${r}`).join('\n');

  return `# FORMAL LEGAL DEMAND — Australian Consumer Law Section 56

**Date Issued**: ${dateIssued}
**Reference**: SN9010-ACL56-${dateIssued.replace(/-/g, '')}
**Generated by**: Sovereign Node 9010 (Forensic Audit System)

---

## 1. Parties

| Role | Name |
|------|------|
| **Consumer** | ${consumerName} |
| **Supplier** | ${supplierName} |

## 2. Material Breach — Goods Do Not Match Description

Under **Australian Consumer Law Section 56**, goods supplied to a consumer by description must correspond with that description.

| Item | Invoice Description | Actual Product | Discrepancy |
|------|-------------------|----------------|-------------|
| Model | ${invoiceSpec} | ${hardwareId} | Specification mismatch |

## 3. Forensic Evidence

### 3.1 Entropy Analysis

| Metric | Value |
|--------|-------|
| Shannon Entropy | ${deceptionReport.entropy.shannonEntropy.toFixed(3)} bits/char |
| Normalized Entropy | ${deceptionReport.entropy.normalizedEntropy.toFixed(3)} |
| Anomaly Flag | ${deceptionReport.entropy.anomalyFlag ? 'YES — possible non-human origin' : 'No'} |

### 3.2 Deceptive Patterns Detected

${patternLines || '- No patterns detected'}

### 3.3 Deception Probability

**${(deceptionReport.deceptionProbability * 100).toFixed(1)}%** — Structural Deception Flag: **${deceptionReport.structuralDeceptionFlag ? 'TRUE' : 'FALSE'}**

### 3.4 Forensic Reasoning

${reasoningLines || '- No forensic reasoning generated'}

${
  bbfbScore
    ? `### 3.5 BBFB Economic Harm Assessment

| LAW Gate | Value | Threshold | Passed |
|----------|-------|-----------|--------|
${bbfbScore.law.map((l) => `| ${l.metric} | ${l.value.toFixed(4)} | ${l.threshold} | ${l.passed ? 'YES' : '**NO**'} |`).join('\n')}

| GRACE Risk | Value |
|------------|-------|
| Raw Penalty | ${bbfbScore.grace.rawPenalty.toFixed(4)} |
| Normalized Penalty | ${bbfbScore.grace.normalizedPenalty.toFixed(4)} |
| Risk Level | **${bbfbScore.grace.riskLevel}** |

| FRUIT Score | Value |
|-------------|-------|
| Composite Value Score | ${bbfbScore.fruit.compositeValueScore.toFixed(6)} |
| CVS Threshold | ${bbfbScore.fruit.threshold} |
| Compliant | ${bbfbScore.fruit.compliant ? 'YES' : '**NO**'} |

**Overall BBFB Compliance**: ${bbfbScore.overallCompliant ? 'COMPLIANT' : '**NON-COMPLIANT — Economic harm substantiated**'}
`
    : ''
}## 4. Demand

Pursuant to the Australian Consumer Law (Schedule 2 of the Competition and Consumer Act 2010), the consumer demands:

1. **Full refund** of the purchase price within **14 business days**; OR
2. **Replacement** with goods matching the invoice description exactly; OR
3. **Cost of correction** (including but not limited to DSP retuning, integration costs, and any consequential loss).

## 5. Consequences of Non-Compliance

Failure to comply within 14 business days will result in:

- Formal complaint to the **Australian Competition and Consumer Commission (ACCC)**
- Referral to the relevant **State/Territory Consumer Affairs office**
- Legal proceedings for breach of statutory consumer guarantees

## 6. Evidence Package

This demand is supported by the forensic audit evidence package generated by Sovereign Node 9010. All entropy calculations, pattern matches, and confidence scores are deterministic and reproducible.

---

**Timestamp**: ${deceptionReport.timestamp}
**Audit Trail**: Sovereign Node 9010 — Groknett ValueForge
`;
}
